services:
  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnet

  php:
    build: ./php
    container_name: php_app
    volumes:
      - ./backend:/var/www/html/backend
    networks:
      - appnet


  postgres:
    image: postgres:15
    container_name: postgres_app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TMS-CIIT
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - appnet


volumes:
  pgdata:

networks:
  appnet:
